title: SF Election Endorsements Matrix
description: >
  An endorsement matrix for the November 2022 San Francisco election.
theme: jekyll-theme-primer
github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/siggy/sfendorsements"
